# -*- coding: utf-8 -*-
"""C115-Logistic-Regression-2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14AsHX0JiydGATx4bHVTJOn3LVN1e0y-Z
"""

import pandas as pd
import plotly.express as px

from google.colab import files
data_to_load = files.upload()

import csv

df = pd.read_csv('data2.csv')

temp = df['Temperature'].tolist()
melted = df['Melted'].tolist()

fig = px.scatter(x = temp, y = melted)
fig.show()

import numpy as np

temp1 = np.array(temp)
melted1 = np.array(melted)

m,c = np.polyfit(temp1, melted1, 1)

y = []

for i in temp1:
    yvalue = m * i + c
    y.append(yvalue)

fig1 = px.scatter(x = temp1, y = melted1)
fig1.update_layout(shapes = [dict(type = 'line', y0 = min(y), y1 = max(y), x0 = min(temp1), x1 = max(temp1) )])
fig1.show()

import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression 

X = np.reshape(temp, (len(temp), 1))
Y = np.reshape(melted, (len(melted), 1))

lr = LogisticRegression()
lr.fit(X,Y)

plt.figure()
plt.scatter(X.ravel(), Y, color = 'orange', zorder = 20)

def model(x):
    return 1 / (1 + np.exp(-x))

xTest = np.linspace(0,5000,10000)
chances = model(xTest * lr.coef_ + lr.intercept_).ravel()

plt.plot(xTest, chances, color = 'blue', linewidth = 2)
plt.axhline(y = 0, color = 'green', linestyle = '-')
plt.axhline(y = 1, color = 'green', linestyle = '-')
plt.axhline(y = 0.5, color = 'black', linestyle = '--')
plt.axvline(x = xTest[6843], color = 'red', linestyle = '--')
plt.ylabel("Y")
plt.xlabel('X')
plt.xlim(3400,3500)
plt.show()

temp2 = float(input("Enter the temperature "))
chances1 = model(temp2 * lr.coef_ + lr.intercept_).ravel()[0]

if chances1 >= 1:
    print("It will be melted")
elif chances1 <= 0.01:
    print("It will not be melted")
elif chances1 <= 0.5:
    print("It might not get melted")    
else :
    print("It may get melted")