# -*- coding: utf-8 -*-
"""C115-Logistic-Regression-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p_wQCB_GaTnT6_scwW0AuCQVq5eTRCw8
"""

import pandas as pd
import plotly.express as px

from google.colab import files
data_to_load = files.upload()

import csv

df = pd.read_csv('data.csv')

score = df['Score'].tolist()
accepted = df['Accepted'].tolist()

fig = px.scatter(x = score, y = accepted)
fig.show()

import numpy as np

score1 = np.array(score)
accepted1 = np.array(accepted)

m,c = np.polyfit(score1, accepted1, 1)

y = []

for i in score1:
    yvalue = m * i + c
    y.append(yvalue)

fig1 = px.scatter(x = score1, y = accepted1)
fig1.update_layout(shapes = [dict(type = 'line', y0 = min(y), y1 = max(y), x0 = min(score1), x1 = max(score1) )])
fig1.show()

import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression 

X = np.reshape(score, (len(score), 1))
Y = np.reshape(accepted, (len(accepted), 1))

lr = LogisticRegression()
lr.fit(X,Y)

plt.figure()
plt.scatter(X.ravel(), Y, color = 'orange', zorder = 20)

def model(x):
    return 1 / (1 + np.exp(-x))

xTest = np.linspace(0,100,200)
chances = model(xTest * lr.coef_ + lr.intercept_).ravel()

plt.plot(xTest, chances, color = 'blue', linewidth = 2)
plt.axhline(y = 0, color = 'green', linestyle = '-')
plt.axhline(y = 1, color = 'green', linestyle = '-')
plt.axhline(y = 0.5, color = 'black', linestyle = '--')
plt.axvline(x = xTest[165], color = 'red', linestyle = '--')
plt.ylabel("Y")
plt.xlabel('X')
plt.xlim(75,85)
plt.show()

userScore = float(input("Enter your marks "))
chances1 = model(userScore * lr.coef_ + lr.intercept_).ravel()[0]

if chances1 >= 1:
    print("Student will be accepted")
elif chances1 <= 0.01:
    print("Student will not be accepted")
elif chances1 <= 0.5:
    print("Student might not get accepted")    
else :
    print("Student may get accepted")

"""sigmoid function will be f(x) = 1/1 + e^-x """